# Generated by Django 6.0.2 on 2026-02-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=100)),
                ('mentor_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
